-- Production-oriented Supabase template for Memory Observatory.
-- Apply this manually after reviewing it in a Supabase branch or staging project.
-- The browser never receives the service role key; writes go through Vercel API routes.

create extension if not exists pgcrypto;

create table if not exists public.memories (
  id text primary key,
  title text not null,
  description text not null default '',
  author text not null default 'Demo',
  chapter text not null default 'memory-room',
  category text not null default 'daily',
  era text not null default 'present',
  place text not null default 'Sin lugar',
  importance integer not null default 1,
  media_url text not null,
  media_type text not null default 'image',
  mood text not null default '#8f5cff',
  linked_memory_id text references public.memories(id) on delete set null,
  date text,
  sort_order integer not null default 0,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.responses (
  id text primary key,
  memory_id text not null references public.memories(id) on delete cascade,
  author text not null default 'Demo',
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.editor_audit_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  subject_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.memories enable row level security;
alter table public.responses enable row level security;
alter table public.editor_audit_events enable row level security;

create index if not exists memories_sort_order_idx on public.memories(sort_order);
create index if not exists memories_date_idx on public.memories(date);
create index if not exists memories_hidden_idx on public.memories(hidden);
create index if not exists responses_memory_id_idx on public.responses(memory_id);
create index if not exists editor_audit_events_created_at_idx on public.editor_audit_events(created_at desc);

drop policy if exists "Published memories are readable" on public.memories;
drop policy if exists "Published responses are readable" on public.responses;
drop policy if exists "No public audit reads" on public.editor_audit_events;

create policy "Published memories are readable"
on public.memories for select
to anon, authenticated
using (hidden = false);

create policy "Published responses are readable"
on public.responses for select
to anon, authenticated
using (
  exists (
    select 1
    from public.memories
    where memories.id = responses.memory_id
      and memories.hidden = false
  )
);

create policy "No public audit reads"
on public.editor_audit_events for select
to anon, authenticated
using (false);

-- No anon/authenticated insert/update/delete policies are defined on purpose.
-- The Vercel API uses SUPABASE_SERVICE_ROLE_KEY server-side, which bypasses RLS
-- and records writes in editor_audit_events. Never expose that key to the browser.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'memory-media',
  'memory-media',
  true,
  52428800,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'video/quicktime'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Keep storage object writes private to the backend/signed-upload flow.
-- createSignedUploadUrl is generated by the service-role API route; clients upload
-- only with that short-lived signed URL, not with broad anon storage policies.
