import type { Memory, RelationshipMilestone, SkyMoment } from '../types/story'

const now = new Date().toISOString()

export const relationshipMilestones: RelationshipMilestone[] = [
  {
    id: 'anchor-convergence',
    date: '2021-06-03',
    title: '03 / 06 / 2021',
    body: 'A neutral anchor for the demo constellation: the point where two sample paths begin to share gravity.',
    kind: 'beginning',
    constellationWeight: 3,
  },
  {
    id: 'anchor-origin-a',
    date: '2019-01-15',
    title: '15 / 01 / 2019',
    body: 'The first sample coordinate, used to show how early milestones shape the atlas.',
    kind: 'birthday',
    constellationWeight: 2,
  },
  {
    id: 'anchor-origin-b',
    date: '2019-09-21',
    title: '21 / 09 / 2019',
    body: 'A second origin point, balancing the map before the shared timeline begins.',
    kind: 'birthday',
    constellationWeight: 2,
  },
  {
    id: 'anchor-first-light',
    date: '2022-02-14',
    title: '14 / 02 / 2022',
    body: 'A symbolic turning point for the public demo: small in the interface, important in the structure.',
    kind: 'kiss',
    constellationWeight: 2,
  },
]

export const skyMoments: SkyMoment[] = [
  { id: 'star-01', date: '2019-01-15', label: '01', x: 18, y: 48, magnitude: 1, tone: 'violet' },
  { id: 'star-02', date: '2019-09-21', label: '02', x: 29, y: 28, magnitude: 0.82, tone: 'ivory' },
  { id: 'star-03', date: '2021-06-03', label: '03', x: 43, y: 54, magnitude: 0.92, tone: 'wine' },
  { id: 'star-04', date: '2022-02-14', label: '04', x: 55, y: 25, magnitude: 0.74, tone: 'ivory' },
  { id: 'star-05', date: '2023-04-08', label: '05', x: 70, y: 41, magnitude: 0.84, tone: 'violet' },
  { id: 'star-06', date: '2024-10-20', label: '06', x: 63, y: 70, magnitude: 0.72, tone: 'wine' },
]

export const memoryCategories = [
  {
    id: 'sacred',
    label: 'Milestones',
    body: 'Important moments that deserve more visual weight in the constellation.',
  },
  {
    id: 'daily',
    label: 'Everyday',
    body: 'Smaller memories that keep the story feeling lived-in and editable.',
  },
  {
    id: 'future',
    label: 'Drafts',
    body: 'Optional placeholder records for ideas that have not become full memories yet.',
  },
] as const

const sampleMedia = (index: number) =>
  `/media/memories/constellation/sample-memory-${String(index).padStart(2, '0')}.jpg`

export const defaultMemories: Memory[] = [
  {
    id: 'sample-memory-origin-a',
    title: 'First coordinate',
    description: 'A sample milestone that demonstrates how the atlas handles an early point in the story.',
    author: 'Demo',
    chapter: 'galaxy',
    category: 'sacred',
    era: 'origin',
    place: 'sample origin',
    importance: 3,
    mediaUrl: sampleMedia(1),
    mediaType: 'image',
    mood: '#8f5cff',
    date: '2019-01-15',
    order: 1,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-origin-b',
    title: 'Second coordinate',
    description: 'A companion anchor used to show how two independent paths can converge later in the map.',
    author: 'Demo',
    chapter: 'galaxy',
    category: 'sacred',
    era: 'origin',
    place: 'sample origin',
    importance: 3,
    mediaUrl: sampleMedia(2),
    mediaType: 'image',
    mood: '#8f5cff',
    date: '2019-09-21',
    order: 2,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-first-signal',
    title: 'First signal',
    description: 'A flexible-date example that stays near the beginning without needing an exact day.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'daily',
    era: 'becoming',
    place: 'example location',
    importance: 1,
    mediaUrl: sampleMedia(3),
    mediaType: 'image',
    mood: '#9b9aa5',
    date: '2021',
    order: 3,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-convergence',
    title: 'Shared orbit',
    description:
      'The central demo record. It shows how a meaningful date becomes the gravity point for nearby memories.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'sacred',
    era: 'becoming',
    place: 'central anchor',
    importance: 3,
    mediaUrl: sampleMedia(4),
    mediaType: 'image',
    mood: '#d84d70',
    date: '2021-06-03',
    order: 4,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-light',
    title: 'First light',
    description:
      'A symbolic milestone with a stronger color and a direct link into the constellation structure.',
    author: 'Demo',
    chapter: 'galaxy',
    category: 'sacred',
    era: 'becoming',
    place: 'quiet scene',
    importance: 3,
    mediaUrl: sampleMedia(5),
    mediaType: 'image',
    mood: '#d84d70',
    date: '2022-02-14',
    order: 5,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-everyday-01',
    title: 'Small ritual',
    description: 'A daily entry that keeps the interface from becoming only a list of big events.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'daily',
    era: 'becoming',
    place: 'everyday route',
    importance: 1,
    mediaUrl: sampleMedia(6),
    mediaType: 'image',
    mood: '#f2c66d',
    date: '2022-08',
    order: 6,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-anniversary-01',
    title: 'First return',
    description: 'A dated record that demonstrates chronological ordering in the trajectory view.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'sacred',
    era: 'present',
    place: 'return point',
    importance: 3,
    mediaUrl: sampleMedia(7),
    mediaType: 'image',
    mood: '#d84d70',
    date: '2023-04-08',
    order: 7,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-gallery',
    title: 'Public gallery test',
    description: 'A neutral sample used to validate media framing, soft edges, and star placement.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'daily',
    era: 'present',
    place: 'demo gallery',
    importance: 1,
    mediaUrl: sampleMedia(8),
    mediaType: 'image',
    mood: '#f2c66d',
    date: '2023-11',
    order: 8,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-linked-note',
    title: 'Linked note',
    description: 'This memory is connected to another one so reviewers can see manual relationship threads.',
    author: 'Demo',
    chapter: 'capsule',
    category: 'sacred',
    era: 'present',
    place: 'linked scene',
    importance: 3,
    mediaUrl: sampleMedia(9),
    mediaType: 'image',
    mood: '#d84d70',
    date: '2023-12-12',
    linkedMemoryId: 'sample-memory-gallery',
    order: 9,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-night-map',
    title: 'Night map',
    description: 'A later milestone that pulls the atlas outward and tests spacing around denser clusters.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'sacred',
    era: 'present',
    place: 'city lights',
    importance: 3,
    mediaUrl: sampleMedia(10),
    mediaType: 'image',
    mood: '#8f5cff',
    date: '2024-10-20',
    order: 10,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-letter',
    title: 'Drafted letter',
    description: 'A letter-style entry used by the generated prose view without exposing personal copy.',
    author: 'Demo',
    chapter: 'capsule',
    category: 'sacred',
    era: 'present',
    place: 'archive note',
    importance: 3,
    mediaUrl: sampleMedia(11),
    mediaType: 'image',
    mood: '#8f5cff',
    date: '2025-02-01',
    order: 11,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-memory-current',
    title: 'Current orbit',
    description:
      'The final seeded entry, showing that the constellation can keep expanding with new uploads.',
    author: 'Demo',
    chapter: 'memory-room',
    category: 'daily',
    era: 'present',
    place: 'latest sample',
    importance: 1,
    mediaUrl: sampleMedia(12),
    mediaType: 'image',
    mood: '#d84d70',
    date: '2025-05-18',
    linkedMemoryId: 'sample-memory-letter',
    order: 12,
    responses: [],
    createdAt: now,
    updatedAt: now,
  },
]
